@startuml

skinparam page 2x2
skinparam pageMargin 5
skinparam pageExternalColor white
skinparam pageBorderColor white
skinparam pageBorderThickness 1

skinparam shadowing true
skinparam linetype ortho
skinparam defaultFontName Helvetica
skinparam defaultFontColor #4B0082
skinparam backgroundColor transparent
skinparam horizontalMargin 20

skinparam BoxPadding 1
skinparam Padding 2

skinparam ArrowColor #4B0082
skinparam ArrowThickness 0.5

skinparam ActivityBackgroundColor #FEB200
skinparam ActivityBarColor #4B0082
skinparam ActivityBorderColor #4B0082
skinparam ActivityBorderThickness 0.5
skinparam ActivityDiamondBackgroundColor #FEB200
skinparam ActivityDiamondBorderColor #4B0082
skinparam ActorBackgroundColor #FEB200 #FEB200
skinparam ActorBorderColor #4B0082
skinparam AgentBackgroundColor #FEB200 #FEB200
skinparam AgentBorderColor #4B0082
skinparam AgentBorderThickness 0.5

skinparam ArtifactBackgroundColor #FEB200
skinparam ArtifactBorderColor #4B0082

skinparam BiddableBackgroundColor #FEB200
skinparam BiddableBorderColor #4B0082
skinparam BoundaryBackgroundColor #FEB200
skinparam BoundaryBorderColor #4B0082
skinparam CardBackgroundColor #FEB200
skinparam CardBorderColor #4B0082
skinparam CardBorderThickness 0.5

skinparam CircledCharacterBackgroundColor #FEB200

skinparam ClassBackgroundColor #FEB200
skinparam ClassBorderColor #4B0082
skinparam ClassBorderThickness 0.5
skinparam ClassHeaderBackgroundColor #FEB200
skinparam ClassStereotypeFontName Arial Narrow
skinparam ClassStereotypeFontStyle Normal
skinparam ClassStereotypeFontSize 10

skinparam CloudBackgroundColor #FEB200
skinparam CloudBorderColor #4B0082

skinparam CollectionsBackgroundColor #FEB200
skinparam CollectionsBorderColor #4B0082

skinparam ComponentBackgroundColor #FEB200
skinparam ComponentBorderColor #4B0082
skinparam ComponentBorderThickness 0.5


skinparam ComponentStereotypeFontName Arial Narrow
skinparam ComponentStereotypeFontSize 5

skinparam ControlBackgroundColor #FEB200
skinparam ControlBorderColor #4B0082

skinparam ControlStereotypeFontName Arial Narrow
skinparam ControlStereotypeFontSize 5

skinparam DatabaseBackgroundColor #FEB200
skinparam DatabaseBorderColor #4B0082

skinparam DatabaseStereotypeFontName Arial Narrow
skinparam DatabaseStereotypeFontSize 5

skinparam DesignedBackgroundColor #FEB200
skinparam DesignedBorderColor #4B0082
skinparam DesignedDomainBorderThickness 0.5

skinparam DesignedDomainStereotypeFontName Arial Narrow
skinparam DesignedDomainStereotypeFontSize 5
skinparam DiagramBorderColor #4B0082
skinparam DiagramBorderThickness 0.5
skinparam DomainBackgroundColor #FEB200
skinparam DomainBorderColor #4B0082
skinparam DomainBorderThickness 0.5

skinparam DomainStereotypeFontName Arial Narrow
skinparam DomainStereotypeFontSize 5

skinparam EntityBackgroundColor #FEB200
skinparam EntityBorderColor #4B0082

skinparam EntityStereotypeFontName Arial Narrow
skinparam EntityStereotypeFontSize 5
skinparam EnumBackgroundColor #FEB200
skinparam FileBackgroundColor #FEB200
skinparam FileBorderColor #4B0082

skinparam FileStereotypeFontName Arial Narrow
skinparam FileStereotypeFontSize 5

skinparam FolderBackgroundColor #FEB200
skinparam FolderBorderColor #4B0082

skinparam FolderStereotypeFontName Arial Narrow
skinparam FolderStereotypeFontSize 5

skinparam FrameBackgroundColor #FEB200
skinparam FrameBorderColor #4B0082

skinparam FrameStereotypeFontName Arial Narrow
skinparam FrameStereotypeFontSize 5

skinparam IconPackageBackgroundColor #FEB200

skinparam IconPrivateBackgroundColor #FEB200
skinparam IconProtectedBackgroundColor #FEB200
skinparam IconPublicBackgroundColor #FEB200
skinparam InterfaceBackgroundColor #FEB200
skinparam InterfaceBorderColor #4B0082

skinparam InterfaceStereotypeFontName Arial Narrow
skinparam InterfaceStereotypeFontSize 5
skinparam LegendBackgroundColor #FEB200
skinparam LegendBorderColor #4B0082
skinparam LegendBorderThickness 0.5

skinparam LexicalBackgroundColor #FEB200
skinparam LexicalBorderColor #4B0082

skinparam MachineBackgroundColor #FEB200
skinparam MachineBorderColor #4B0082
skinparam MachineBorderThickness 0.5

skinparam MachineStereotypeFontName Arial Narrow
skinparam MachineStereotypeFontSize 5

skinparam NodeBackgroundColor #FEB200
skinparam NodeBorderColor #4B0082

skinparam NodeStereotypeFontName Arial Narrow
skinparam NodeStereotypeFontSize 5

skinparam NoteBackgroundColor #FEB200
skinparam NoteBorderColor #4B0082
skinparam NoteBorderThickness 0.5

skinparam ObjectBackgroundColor #FEB200
skinparam ObjectBorderColor #4B0082
skinparam ObjectBorderThickness 0.5

skinparam ObjectStereotypeFontName Arial Narrow
skinparam ObjectStereotypeFontSize 5

skinparam PackageBackgroundColor transparent
skinparam PackageBorderColor #4B0082
skinparam PackageBorderThickness 0.5

skinparam PackageStereotypeFontName Arial Narrow
skinparam PackageStereotypeFontSize 5

skinparam ParticipantBackgroundColor #FEB200
skinparam ParticipantBorderColor #4B0082

skinparam ParticipantStereotypeFontName Arial Narrow
skinparam ParticipantStereotypeFontSize 5
skinparam PartitionBackgroundColor #FEB200
skinparam PartitionBorderColor #4B0082
skinparam PartitionBorderThickness 0.5

skinparam QueueBackgroundColor #FEB200
skinparam QueueBorderColor #4B0082

skinparam QueueStereotypeFontName Arial Narrow
skinparam QueueStereotypeFontSize 5

skinparam RectangleBackgroundColor #FEB200
skinparam RectangleBorderColor #4B0082
skinparam RectangleBorderThickness 0.5

skinparam RectangleStereotypeFontName Arial Narrow
skinparam RectangleStereotypeFontSize 5

skinparam RequirementBackgroundColor #FEB200
skinparam RequirementBorderColor #4B0082
skinparam RequirementBorderThickness 0.5

skinparam RequirementStereotypeFontName Arial Narrow
skinparam RequirementStereotypeFontSize 5

skinparam SequenceActorBorderThickness 0.5
skinparam SequenceBoxBackgroundColor #FEB200
skinparam SequenceBoxBorderColor #4B0082

skinparam SequenceDividerBackgroundColor #FEB200
skinparam SequenceDividerBorderColor #4B0082
skinparam SequenceDividerBorderThickness 0.5

skinparam SequenceGroupBackgroundColor #FEB200
skinparam SequenceGroupBodyBackgroundColor #FEB200
skinparam SequenceGroupBorderColor #4B0082
skinparam SequenceGroupBorderThickness 0.5

skinparam SequenceLifeLineBackgroundColor #FEB200
skinparam SequenceLifeLineBorderColor #4B0082
skinparam SequenceLifeLineBorderThickness 0.5

skinparam SequenceParticipantBorderThickness 0.5

skinparam SequenceReferenceBackgroundColor #FEB200
skinparam SequenceReferenceBorderColor #4B0082
skinparam SequenceReferenceBorderThickness 0.5

skinparam SequenceReferenceHeaderBackgroundColor #FEB200

skinparam SequenceStereotypeFontName Arial Narrow
skinparam SequenceStereotypeFontSize 5

skinparam StackBackgroundColor #FEB200
skinparam StackBorderColor #4B0082

skinparam StackStereotypeFontName Arial Narrow
skinparam StackStereotypeFontSize 5

skinparam StateBackgroundColor #FEB200
skinparam StateBorderColor #4B0082

skinparam StereotypeABackgroundColor #FFD014
skinparam StereotypeABorderColor #4B0082
skinparam StereotypeCBackgroundColor #FFD014
skinparam StereotypeCBorderColor #4B0082
skinparam StereotypeEBackgroundColor #FFD014
skinparam StereotypeEBorderColor #4B0082
skinparam StereotypeIBackgroundColor #FFD014
skinparam StereotypeIBorderColor #4B0082
skinparam StereotypeNBackgroundColor #FFD014
skinparam StereotypeNBorderColor #4B0082
skinparam StorageBackgroundColor #FFD014
skinparam StorageBorderColor #4B0082

skinparam StorageStereotypeFontName Arial Narrow
skinparam StorageStereotypeFontSize 5

skinparam SwimlaneBorderColor #4B0082
skinparam SwimlaneBorderThickness 0.5

skinparam TitleBackgroundColor #FEB200
skinparam TitleBorderColor #4B0082
skinparam TitleBorderThickness 0.5

skinparam UsecaseBackgroundColor #FEB200
skinparam UsecaseBorderColor #4B0082
skinparam UsecaseBorderThickness 0.5

skinparam UsecaseStereotypeFontName Arial Narrow
skinparam UsecaseStereotypeFontSize 5

@enduml